// Package data — plans.go provides functions to detect and read Copilot CLI
// plan.md files from session-state directories.
package data

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/jongio/dispatch/internal/validate"
)

// maxPlanFileSize caps the number of bytes read from a plan.md file to
// prevent memory exhaustion from adversarially large files.
const maxPlanFileSize = 64 * 1024 // 64 KB

// ScanAllPlans reads the session-state directory and returns a map of
// session ID → true for every session that has a non-empty plan.md file.
// It discovers sessions from the filesystem directly, matching the
// pattern used by ScanAttention.
func ScanAllPlans() map[string]bool {
	stateDir := sessionStatePath()
	if stateDir == "" {
		return nil
	}

	entries, err := os.ReadDir(stateDir)
	if err != nil {
		return nil
	}

	result := make(map[string]bool, len(entries)/4)
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		id := e.Name()
		if !validate.SessionID(id) {
			continue
		}
		planPath := filepath.Join(stateDir, id, "plan.md")
		info, err := os.Lstat(planPath)
		if err != nil {
			continue
		}
		if info.Mode().IsRegular() && info.Size() > 0 {
			result[id] = true
		}
	}
	return result
}

// ReadPlanContent reads the plan.md file for the given session ID.
// Returns the plan content as a string, capped at maxPlanFileSize bytes.
// Returns an empty string and an error if the file cannot be read or the
// session ID is invalid.
func ReadPlanContent(sessionID string) (string, error) {
	path, err := PlanFilePath(sessionID)
	if err != nil {
		return "", err
	}

	// Use Lstat to reject symlinks before reading.
	info, err := os.Lstat(path)
	if err != nil {
		return "", err
	}
	if !info.Mode().IsRegular() {
		return "", &os.PathError{Op: "read", Path: path, Err: os.ErrInvalid}
	}

	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	// Read up to maxPlanFileSize bytes using LimitReader to handle
	// short reads correctly (f.Read is not guaranteed to fill the buffer).
	content, err := io.ReadAll(io.LimitReader(f, maxPlanFileSize))
	if err != nil {
		return "", err
	}
	return string(content), nil
}

// PlanFilePath returns the absolute path to the plan.md file for the
// given session ID. Returns an error if the session ID is invalid or
// the session-state directory cannot be resolved.
func PlanFilePath(sessionID string) (string, error) {
	if !validate.SessionID(sessionID) {
		return "", &os.PathError{Op: "open", Path: sessionID, Err: os.ErrInvalid}
	}

	stateDir := sessionStatePath()
	if stateDir == "" {
		return "", &os.PathError{Op: "open", Path: sessionID, Err: os.ErrNotExist}
	}

	path := filepath.Join(stateDir, sessionID, "plan.md")

	// Verify the resolved path is still under the session-state directory
	// to prevent path traversal via crafted session IDs like "a/../../../etc".
	cleaned := filepath.Clean(path)
	if runtime.GOOS == "windows" {
		if !strings.HasPrefix(strings.ToLower(cleaned), strings.ToLower(stateDir+string(filepath.Separator))) {
			return "", &os.PathError{Op: "open", Path: sessionID, Err: os.ErrPermission}
		}
	} else {
		if !strings.HasPrefix(cleaned, stateDir+string(filepath.Separator)) {
			return "", &os.PathError{Op: "open", Path: sessionID, Err: os.ErrPermission}
		}
	}

	return path, nil
}

// ---------------------------------------------------------------------------
// Continuation plan writing
// ---------------------------------------------------------------------------

// remainingWorkHeader is the sentinel heading used to detect an existing
// auto-generated remaining-work section in a plan.md file. It is used
// both when appending new content and when replacing a stale section.
const remainingWorkHeader = "## Remaining Work (auto-generated by dispatch)"

// WriteContinuationPlan appends (or replaces) a "Remaining Work" section
// in the session's plan.md file. If the plan already contains a section
// with the sentinel header, that section is replaced in-place so that
// repeated scans do not duplicate content.
//
// The function creates the plan.md file (and its parent directory) if
// neither exists, following the same path-safety rules as PlanFilePath.
func WriteContinuationPlan(sessionID string, remaining []string, summary string) error {
	if len(remaining) == 0 && summary == "" {
		return nil // nothing to write
	}

	path, err := PlanFilePath(sessionID)
	if err != nil {
		return fmt.Errorf("resolving plan path: %w", err)
	}

	// Ensure the session directory exists (it may not if the session-state
	// was created by the store but never had a plan written).
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating session dir: %w", err)
	}

	// Read any existing content — missing file is fine (we'll create it).
	existing, err := readFileIfExists(path)
	if err != nil {
		return fmt.Errorf("reading existing plan: %w", err)
	}

	newSection := buildRemainingSection(remaining, summary)
	updated := mergeRemainingSection(existing, newSection)

	// Open-then-Fstat eliminates the TOCTOU window between Lstat and
	// WriteFile: we verify the opened fd itself is a regular file (or
	// newly created) before writing any bytes.
	//nolint:gosec // 0644 is the standard permission for plan.md files
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o644)
	if err != nil {
		return fmt.Errorf("opening plan for write: %w", err)
	}
	defer f.Close()

	info, err := f.Stat()
	if err != nil {
		return fmt.Errorf("stat plan fd: %w", err)
	}
	if !info.Mode().IsRegular() {
		return &os.PathError{Op: "write", Path: path, Err: os.ErrInvalid}
	}

	if _, err := f.WriteString(updated); err != nil {
		return fmt.Errorf("writing plan: %w", err)
	}
	return nil
}

// readFileIfExists reads a regular file at path. It returns ("", nil) if
// the file does not exist or is not a regular file. Uses open-then-Fstat
// to avoid a TOCTOU window between stat and open.
func readFileIfExists(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", err
	}
	defer f.Close()
	info, err := f.Stat()
	if err != nil {
		return "", err
	}
	if !info.Mode().IsRegular() {
		return "", nil
	}
	content, err := io.ReadAll(io.LimitReader(f, maxPlanFileSize))
	if err != nil {
		return "", err
	}
	return string(content), nil
}

// buildRemainingSection constructs the markdown text for the remaining
// work section including the sentinel header.
func buildRemainingSection(remaining []string, summary string) string {
	var b strings.Builder
	b.WriteString(remainingWorkHeader)
	b.WriteString("\n\nThe following items were identified as incomplete:\n\n")
	for _, item := range remaining {
		b.WriteString("- [ ] ")
		b.WriteString(item)
		b.WriteByte('\n')
	}
	if summary != "" {
		b.WriteString("\nSummary: ")
		b.WriteString(summary)
		b.WriteByte('\n')
	}
	return b.String()
}

// mergeRemainingSection replaces an existing remaining-work section in
// the plan (identified by remainingWorkHeader) with newSection.
// If no existing section is found, newSection is appended with a
// separating blank line.
func mergeRemainingSection(existing, newSection string) string {
	idx := strings.Index(existing, remainingWorkHeader)
	if idx < 0 {
		// No existing section — append.
		if existing == "" {
			return newSection
		}
		trimmed := strings.TrimRight(existing, "\n")
		return trimmed + "\n\n" + newSection
	}

	// Found existing section — find the end of it. The section ends at
	// the next heading of the same or higher level (## or #), or at EOF.
	rest := existing[idx+len(remainingWorkHeader):]
	endOffset := len(rest) // default: section goes to EOF
	lines := strings.Split(rest, "\n")
	pos := 0
	for i, line := range lines {
		if i == 0 {
			// Skip the header line itself (already consumed the prefix).
			pos += len(line) + 1
			continue
		}
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "## ") || strings.HasPrefix(trimmed, "# ") {
			endOffset = pos
			break
		}
		pos += len(line) + 1
	}

	before := strings.TrimRight(existing[:idx], "\n")
	after := strings.TrimLeft(rest[endOffset:], "\n")

	var b strings.Builder
	if before != "" {
		b.WriteString(before)
		b.WriteString("\n\n")
	}
	b.WriteString(newSection)
	if after != "" {
		b.WriteByte('\n')
		b.WriteString(after)
	}
	return b.String()
}
